apiVersion: v1
kind: Service
metadata:
  name: whiteduck-api # Name of the service (also DNS name for access from other Services)
spec:
  selector: # Tags for which pods the service routes
    app: whiteduck
    tier: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: http # port alias, configured in deployment