apiVersion: v1
kind: Service
metadata:
  name: whiteduck-loadbalancer
spec:
  selector:
    app: whiteduck
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: http
  type: LoadBalancer