apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: whiteduck-frontend
spec:
  selector:
    matchLabels:
      app: whiteduck
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: whiteduck
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: "stivik/wdaksfrontend"
          ports:
            - name: http
              containerPort: 3000